apiVersion: apps/v1
kind: Deployment
metadata:
  name: aux-service
  namespace: aux-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aux-service
  template:
    metadata:
      labels:
        app: aux-service
    spec:
      containers:
        - name: aux-service
          image: lpdourado/aux-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: AWS_REGION
              value: "eu-west-1"
---
apiVersion: v1
kind: Service
metadata:
  name: aux-service
  namespace: aux-service
spec:
  selector:
    app: aux-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP