apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-config
  namespace: monitoring
data:
  additional-scrape-configs.yaml: |
    scrape_configs:
      - job_name: "fastapi-services"
        metrics_path: "/metrics"
        static_configs:
          - targets: 
              - "main-api.cloud-engineer-challenge.svc.cluster.local:8000"
              - "aux-service.cloud-engineer-challenge.svc.cluster.local:8001"
