apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-api
  namespace: cloud-engineer-challenge
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::890742573274:role/GitHubActionsOIDC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: cloud-engineer-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
    spec:
      serviceAccountName: main-api
      containers:
        - name: main-api
          image: lpdourado/main-api:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: cloud-engineer-challenge
spec:
  selector:
    app: main-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP