apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: cloud-engineer-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
    spec:
      containers:
        - name: main-api
          image: lpdourado/main-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: AUX_SERVICE_URL
              value: "http://aux-service:8001"
            - name: AWS_REGION
              value: "eu-west-1"
            - name: AWS_PROFILE
              value: "default"
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
      volumes:
        - name: aws-credentials
          hostPath:
            path: /home/ubuntu/.aws
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: cloud-engineer-challenge
spec:
  selector:
    app: main-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP